
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'JUGADOR LLAVE NAME PUERTA \n           todo : expression\n               | empty\n          \n           empty :\n          expression : NAME\n           expression : JUGADORexpression : LLAVEexpression : PUERTA'
    
_lr_action_items = {'NAME':([0,],[4,]),'JUGADOR':([0,],[5,]),'LLAVE':([0,],[6,]),'PUERTA':([0,],[7,]),'$end':([0,1,2,3,4,5,6,7,],[-3,0,-1,-2,-4,-5,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'todo':([0,],[1,]),'expression':([0,],[2,]),'empty':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> todo","S'",1,None,None,None),
  ('todo -> expression','todo',1,'p_rpg','rpgApp.py',56),
  ('todo -> empty','todo',1,'p_rpg','rpgApp.py',57),
  ('empty -> <empty>','empty',0,'p_empty','rpgApp.py',66),
  ('expression -> NAME','expression',1,'p_expname','rpgApp.py',72),
  ('expression -> JUGADOR','expression',1,'p_moveplayer','rpgApp.py',82),
  ('expression -> LLAVE','expression',1,'p_key','rpgApp.py',87),
  ('expression -> PUERTA','expression',1,'p_doorstatur','rpgApp.py',92),
]
