
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DISTANCIA ENTERO FLOTANTE\n            comandos : expresion\n                     | empty\n            \n            expresion : DISTANCIA numero\n                  \n            \n            numero : ENTERO\n                   | FLOTANTE\n            \n            empty :\n            '
    
_lr_action_items = {'DISTANCIA':([0,],[4,]),'$end':([0,1,2,3,5,6,7,],[-6,0,-1,-2,-3,-4,-5,]),'ENTERO':([4,],[6,]),'FLOTANTE':([4,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comandos':([0,],[1,]),'expresion':([0,],[2,]),'empty':([0,],[3,]),'numero':([4,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comandos","S'",1,None,None,None),
  ('comandos -> expresion','comandos',1,'p_comandos','GUIApplication.py',60),
  ('comandos -> empty','comandos',1,'p_comandos','GUIApplication.py',61),
  ('expresion -> DISTANCIA numero','expresion',2,'p_expresion','GUIApplication.py',69),
  ('numero -> ENTERO','numero',1,'p_expresion_int_float','GUIApplication.py',77),
  ('numero -> FLOTANTE','numero',1,'p_expresion_int_float','GUIApplication.py',78),
  ('empty -> <empty>','empty',0,'p_empty','GUIApplication.py',89),
]
