
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ESTADO NAME REINICIOS SOLICITUD \n            todo : expression\n                 | empty\n            \n            empty :\n            expression : SOLICITUDexpression : REINICIOSexpression : ESTADOexpression : NAME\n            '
    
_lr_action_items = {'SOLICITUD':([0,],[4,]),'REINICIOS':([0,],[5,]),'ESTADO':([0,],[6,]),'NAME':([0,],[7,]),'$end':([0,1,2,3,4,5,6,7,],[-3,0,-1,-2,-4,-5,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'todo':([0,],[1,]),'expression':([0,],[2,]),'empty':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> todo","S'",1,None,None,None),
  ('todo -> expression','todo',1,'p_Iniciar','Arranque_Sistema.py',69),
  ('todo -> empty','todo',1,'p_Iniciar','Arranque_Sistema.py',70),
  ('empty -> <empty>','empty',0,'p_empty','Arranque_Sistema.py',78),
  ('expression -> SOLICITUD','expression',1,'p_solicitud','Arranque_Sistema.py',85),
  ('expression -> REINICIOS','expression',1,'p_Reiniciar','Arranque_Sistema.py',90),
  ('expression -> ESTADO','expression',1,'p_estado','Arranque_Sistema.py',95),
  ('expression -> NAME','expression',1,'p_expname','Arranque_Sistema.py',100),
]
